"""Corpus statistics and the cleaning-funnel report (M2 deliverable).

Two things get reported:

- **The funnel**: how many pairs each filter stage dropped. This is the single
  most useful artifact for tuning a data pipeline — if 90% of a source dies at
  the length-ratio stage, either the source is garbage or the threshold is
  wrong, and only the funnel tells you which. Silent drops are how data bugs
  hide, so every stage is counted (cf. the "no silent caps" principle).
- **Length distributions** of the surviving corpus, per language, so we can
  sanity-check against expectations and set the model's max-length.
"""

from __future__ import annotations

import statistics
from dataclasses import dataclass, field


@dataclass
class Funnel:
    """Ordered per-stage drop counts for one source (insertion order = order
    filters ran). ``kept`` is the count that survived everything."""

    source: str
    input_pairs: int = 0
    dropped: dict[str, int] = field(default_factory=dict)
    kept: int = 0

    def drop(self, stage: str, n: int = 1) -> None:
        self.dropped[stage] = self.dropped.get(stage, 0) + n

    def as_dict(self) -> dict:
        return {
            "source": self.source,
            "input_pairs": self.input_pairs,
            "dropped": dict(self.dropped),
            "kept": self.kept,
            "keep_rate": round(self.kept / self.input_pairs, 4) if self.input_pairs else 0.0,
        }


def length_stats(values: list[int]) -> dict:
    """Mean/p50/p95/max of a list of lengths (0s if empty)."""
    if not values:
        return {"mean": 0.0, "p50": 0, "p95": 0, "max": 0}
    ordered = sorted(values)

    def pctl(p: int) -> int:
        k = max(0, min(len(ordered) - 1, round((p / 100) * (len(ordered) - 1))))
        return ordered[k]

    return {
        "mean": round(statistics.fmean(values), 2),
        "p50": pctl(50),
        "p95": pctl(95),
        "max": ordered[-1],
    }


def render_report(
    config_name: str,
    seed: int,
    funnels: list[Funnel],
    ja_lens: list[int],
    en_lens: list[int],
    split_counts: dict[str, int],
) -> str:
    """Render the M2 corpus report as Markdown."""
    total_in = sum(f.input_pairs for f in funnels)
    total_kept = sum(f.kept for f in funnels)
    stages = _all_stages(funnels)
    lines = [
        "# M2 — Parallel corpus build report",
        "",
        f"Generated by `scripts/build_corpus.py` from `{config_name}` (seed {seed}).",
        "Filter thresholds and their rationale: ADR-013. Offline neural filters "
        "(fastText langid, LaBSE): ADR-014.",
        "",
        "## Cleaning funnel (per source): pairs dropped at each stage",
        "",
        "| source | input | " + " | ".join(stages) + " | kept | keep % |",
        "|:--|--:|" + "|".join(["--:"] * (len(stages) + 2)) + "|",
    ]
    for f in funnels:
        stage_cells = " | ".join(str(f.dropped.get(s, 0)) for s in stages)
        rate = f"{100 * f.kept / f.input_pairs:.1f}" if f.input_pairs else "0.0"
        lines.append(f"| {f.source} | {f.input_pairs} | {stage_cells} | {f.kept} | {rate} |")
    # Totals row: sum each stage across sources so every column stays aligned.
    total_cells = " | ".join(f"**{sum(f.dropped.get(s, 0) for f in funnels)}**" for s in stages)
    overall = f"{100 * total_kept / total_in:.1f}" if total_in else "0.0"
    lines.append(f"| **all** | **{total_in}** | {total_cells} | **{total_kept}** | **{overall}** |")

    js, es = length_stats(ja_lens), length_stats(en_lens)
    lines += [
        "",
        "## Surviving corpus — length (characters)",
        "",
        "| side | mean | p50 | p95 | max |",
        "|:--|--:|--:|--:|--:|",
        f"| ja | {js['mean']} | {js['p50']} | {js['p95']} | {js['max']} |",
        f"| en | {es['mean']} | {es['p50']} | {es['p95']} | {es['max']} |",
        "",
        "## Splits",
        "",
        "| split | pairs |",
        "|:--|--:|",
    ]
    for name, count in split_counts.items():
        lines.append(f"| {name} | {count} |")
    lines.append("")
    lines.append("Artifacts: `data/processed/{train,valid,test}.jsonl`.")
    lines.append("")
    return "\n".join(lines)


# The order filters actually run in, so the report reads like the pipeline.
_CANONICAL_STAGE_ORDER = ["length", "ratio", "script", "dedup", "langid", "labse"]


def _all_stages(funnels: list[Funnel]) -> list[str]:
    """Stage names present across funnels, in canonical pipeline order (any
    unrecognised stage is appended at the end)."""
    present = {stage for f in funnels for stage in f.dropped}
    ordered = [s for s in _CANONICAL_STAGE_ORDER if s in present]
    ordered += [s for s in present if s not in _CANONICAL_STAGE_ORDER]
    return ordered
