"""Train the M1 joint Ja+En byte-level BPE tokenizer sweep.

For each vocab size in the config, trains a tokenizer on the joint corpus,
saves it to ``output.dir/tokenizer-{N}k.json``, measures tokens/sentence per
language, and writes the comparison table to ``output.report``. Logs the
sweep to W&B (CLAUDE.md rule #4) unless ``--no-wandb`` is passed.

    uv run python scripts/train_tokenizer.py --config configs/m1_tokenizer.yaml
    uv run python scripts/train_tokenizer.py --config configs/m1_tokenizer.yaml --no-wandb
"""

from __future__ import annotations

import argparse
import statistics
from pathlib import Path

import yaml

from kanjiland.tokenizer import Tokenizer


def _read_lines(path: Path, max_lines: int | None) -> list[str]:
    lines: list[str] = []
    with path.open(encoding="utf-8") as f:
        for i, line in enumerate(f):
            if max_lines is not None and i >= max_lines:
                break
            line = line.rstrip("\n")
            if line:
                lines.append(line)
    return lines


def _size_label(vocab_size: int) -> str:
    return f"{vocab_size // 1000}k" if vocab_size % 1000 == 0 else str(vocab_size)


def _lang_stats(tok: Tokenizer, lines: list[str]) -> dict[str, float]:
    tok_counts = [len(tok.encode(s)) for s in lines]
    char_counts = [len(s) for s in lines]
    n_tok = sum(tok_counts)
    return {
        "sentences": len(lines),
        "tokens_per_sentence_mean": statistics.mean(tok_counts),
        "tokens_per_sentence_p95": _pctl(tok_counts, 95),
        "chars_per_token": (sum(char_counts) / n_tok) if n_tok else 0.0,
    }


def _pctl(xs: list[int], p: int) -> int:
    if not xs:
        return 0
    ordered = sorted(xs)
    k = max(0, min(len(ordered) - 1, round((p / 100) * (len(ordered) - 1))))
    return ordered[k]


def _render_report(config_path: Path, rows: list[dict], seed: int, sample_n: int) -> str:
    lines = [
        "# M1 — Tokenizer comparison (joint Ja+En byte-level BPE)",
        "",
        f"Generated by `scripts/train_tokenizer.py` from `{config_path}` (seed {seed}).",
        f"Stats over a seeded uniform random sample of {sample_n} sentence pairs.",
        "Pre-tokenizer: script-aware runs. Lower tokens/sentence = shorter",
        "sequences = cheaper training and inference; higher chars/token = more",
        "text packed per token. See ADR-012 (resolution deferred to the M5 ablation).",
        "",
        "| vocab | merges | ja tok/sent | ja p95 | ja char/tok | en tok/sent | en p95 | en char/tok |",
        "|------:|-------:|------------:|-------:|------------:|------------:|-------:|------------:|",
    ]
    for r in rows:
        ja, en = r["ja"], r["en"]
        lines.append(
            f"| {r['vocab_size']} | {r['merges']} "
            f"| {ja['tokens_per_sentence_mean']:.2f} | {ja['tokens_per_sentence_p95']} "
            f"| {ja['chars_per_token']:.2f} "
            f"| {en['tokens_per_sentence_mean']:.2f} | {en['tokens_per_sentence_p95']} "
            f"| {en['chars_per_token']:.2f} |"
        )
    lines += [
        "",
        "Artifacts: `data/processed/tokenizer-{8,16,32}k.json`.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--config", required=True, type=Path)
    ap.add_argument("--no-wandb", action="store_true", help="skip W&B logging")
    args = ap.parse_args()

    config = yaml.safe_load(args.config.read_text())
    seed = config.get("seed", 1)

    from kanjiland.train.seed import seed_everything

    seed_everything(seed)

    corpus_cfg = config["corpus"]
    max_lines = corpus_cfg.get("max_lines")
    ja = _read_lines(Path(corpus_cfg["ja"]), max_lines)
    en = _read_lines(Path(corpus_cfg["en"]), max_lines)
    joint = ja + en
    print(f"corpus: {len(ja)} ja + {len(en)} en = {len(joint)} lines")

    # Uniform random sample for the stats — the corpus is sorted short->long
    # (Anki deck order), so a head slice would be badly length-biased. `random`
    # was seeded above, so this is reproducible.
    import random

    sample_n = min(config.get("eval", {}).get("sample_lines", 5000), len(ja))
    idx = sorted(random.sample(range(len(ja)), sample_n))
    ja_sample = [ja[i] for i in idx]
    en_sample = [en[i] for i in idx]

    out_dir = Path(config["output"]["dir"])
    rows: list[dict] = []

    run = None
    if not args.no_wandb:
        from kanjiland.train.wandb_init import init_run

        run = init_run(args.config, extra_metadata={"corpus_lines": len(joint)})

    for vocab_size in config["vocab_sizes"]:
        label = _size_label(vocab_size)
        print(f"\n=== training vocab {vocab_size} ({label}) ===")
        tok = Tokenizer.train(joint, vocab_size=vocab_size, verbose=True)
        out_path = out_dir / f"tokenizer-{label}.json"
        tok.save(out_path)
        print(f"saved {out_path}  (actual vocab {tok.vocab_size}, {len(tok.merges)} merges)")

        row = {
            "vocab_size": vocab_size,
            "actual_vocab": tok.vocab_size,
            "merges": len(tok.merges),
            "ja": _lang_stats(tok, ja_sample),
            "en": _lang_stats(tok, en_sample),
        }
        rows.append(row)
        print(
            f"  ja {row['ja']['tokens_per_sentence_mean']:.2f} tok/sent, "
            f"en {row['en']['tokens_per_sentence_mean']:.2f} tok/sent"
        )
        if run is not None:
            run.log(
                {
                    "vocab_size": vocab_size,
                    "ja_tokens_per_sentence": row["ja"]["tokens_per_sentence_mean"],
                    "en_tokens_per_sentence": row["en"]["tokens_per_sentence_mean"],
                    "ja_chars_per_token": row["ja"]["chars_per_token"],
                    "en_chars_per_token": row["en"]["chars_per_token"],
                }
            )

    report = _render_report(args.config, rows, seed, sample_n)
    report_path = Path(config["output"]["report"])
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(report, encoding="utf-8")
    print(f"\nwrote {report_path}")
    print("\n" + report)

    if run is not None:
        run.finish()


if __name__ == "__main__":
    main()
